export const STAGE_ORDER = [
  'REQUIREMENT_SPECIFICATION',
  'BASIC_LAYOUT_PLANNING',
  'TECH_STACK_APPROVAL',
  'DEVELOPMENT',
  'TESTING',
  'DEPLOYMENT',
  'MAINTENANCE',
  'FEATURE_ENHANCEMENTS',
];

export const PRIORITY_LEVELS = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

export const PROJECT_STATUSES = ['ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED'];

export const TASK_STATUSES = ['NOT_STARTED', 'IN_PROGRESS', 'UNDER_REVIEW', 'BLOCKED', 'COMPLETED'];
